import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedTheme = localStorage.getItem('flash-theme') || '';
                  // Note: Replace these placeholders with your actual font class values
                  const fontClasses = 'geist-sans-variable geist-mono-variable antialiased';
                  if (savedTheme) {
                    document.body.className = savedTheme + ' ' + fontClasses;
                  } else {
                    document.body.className = fontClasses;
                  }
                } catch (e) {
                  // Fallback font classes - replace with your actual values
                  document.body.className = 'geist-sans-variable geist-mono-variable antialiased';
                }
              })();
            `,
          }}
        />
      </head>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
